version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/quarkus-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
