# Example secret manifest. Values are populated from GitHub Actions during
# deployment, so this file serves only as a reference.
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
  namespace: eventflow
stringData:
  client-id: "YOUR_CLIENT_ID"
  client-secret: "YOUR_CLIENT_SECRET"
  auth-server-url: "https://accounts.google.com"
  auth-uri: "https://accounts.google.com/o/oauth2/v2/auth"
  token-uri: "https://oauth2.googleapis.com/token"
  jwks-uri: "https://www.googleapis.com/oauth2/v1/certs"
  redirect-uri: "https://eventflow.opensourcesantiago.io/callback"
