source "https://rubygems.org"

gem "jekyll", "~> 4.3"

group :jekyll_plugins do
  gem "jekyll-archives", "~> 2.2", ">= 2.2.1"
  gem "jekyll-seo-tag", "~> 2.8"
  gem "jekyll-sitemap", "~> 1.4"
end

gem "jekyll-theme-chirpy", "~> 6.4"

gem "webrick", "~> 1.8"
