name: Build Native

on:
  push:
    branches: ["main"]

jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate reflection config with GraalVM agent
        working-directory: quarkus-app
        run: |
          mvn -DskipTests package
          java -agentlib:native-image-agent=config-output-dir=target/native-image-config -jar target/*-runner.jar &
          AGENT_PID=$!
          sleep 5
          curl -f http://localhost:8080/q/health || true
          kill $AGENT_PID

      - name: Build native binary
        working-directory: quarkus-app
        run: mvn package -Pnative -DskipTests -Dquarkus.native.container-build=true "-Dquarkus.native.additional-build-args=-H:ConfigurationFileDirectories=target/native-image-config"

      - name: Verify native binary exists
        run: ls quarkus-app/target/*-runner

      - name: Build Docker image
        working-directory: quarkus-app
        run: |
          docker build -f src/main/docker/Dockerfile.native -t quay.io/sergio_canales_e/eventflow:latest .

      - name: Push Docker image
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          echo "$QUAY_PASSWORD" | docker login quay.io -u "$QUAY_USERNAME" --password-stdin
          docker push quay.io/sergio_canales_e/eventflow:latest
