name: Build Native on Build Completion

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build-native:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build-native.yml
    secrets: inherit
