---
name: Deploy to GKE on Deployment Changes

'on':
  push:
    branches: ['main']
    paths:
      - 'deployment/**'
  pull_request:
    branches: ['main']
    paths:
      - 'deployment/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
