name: Deploy on Build Native Completion

on:
  workflow_run:
    workflows: ["Build Native on Build Completion"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
