name: Build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build with Maven
        run: mvn -B -f quarkus-app/pom.xml package
      - name: Enable auto-merge
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main' }}
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
