name: PR CI (Build, Native, SBOM/Scan)

on:
  pull_request:
    branches: [main]
    paths:
      - 'quarkus-app/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
      - name: Derive version
        run: |
          cd quarkus-app
          VERSION="$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          cd -
          echo "## Version derivada: $VERSION" >> $GITHUB_STEP_SUMMARY
      - name: Build & test
        run: mvn -B -f quarkus-app/pom.xml package

  build-native:
    needs: build
    uses: ./.github/workflows/build-native.yml
    secrets: inherit
