name: sbom-and-scan

on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 6 * * 1"  # lunes 06:00 UTC

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ${{ vars.REGISTRY || 'quay.io' }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME || github.repository }}
  IMAGE: ${{ (vars.REGISTRY || 'quay.io') }}/${{ vars.IMAGE_NAME || github.repository }}:${{ github.sha }}
  SECURITY_GATING: ${{ vars.SECURITY_GATING || 'permissive' }}
  COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

jobs:
  build-sbom-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/dependency-review-action@v4
        if: ${{ github.event_name == 'pull_request' }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build app & dependency SBOM
        working-directory: quarkus-app
        run: ./mvnw -B -DskipTests verify

      - name: Build image
        run: docker build -f quarkus-app/src/main/docker/Dockerfile.jvm -t "$IMAGE" quarkus-app

      - name: Generate image SBOM (Syft CycloneDX)
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE }}
          format: cyclonedx-json
          output-file: sbom-image.cdx.json
          upload-artifact: false

      - name: Grype report (no-fail) - table/json/sarif
        run: |
          TARGET="${REF:-$IMAGE}"
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.docker/config.json:/root/.docker/config.json:ro" \
            anchore/grype:latest "$TARGET" -o table > grype-report.txt || true
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.docker/config.json:/root/.docker/config.json:ro" \
            anchore/grype:latest "$TARGET" -o json  > grype-report.json || true
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.docker/config.json:/root/.docker/config.json:ro" \
            anchore/grype:latest "$TARGET" -o sarif > grype-report.sarif || true
          if [ ! -s grype-report.sarif ]; then
            echo '{"$schema":"https://json.schemastore.org/sarif-2.1.0.json","version":"2.1.0","runs":[{"tool":{"driver":{"name":"grype"}},"results":[]}]}' > grype-report.sarif
          fi

      - name: Upload SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: sboms
          path: |
            quarkus-app/target/bom.json
            sbom-image.cdx.json

      - name: Upload Grype reports (artifacts)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-reports
          path: |
            grype-report.txt
            grype-report.json
            grype-report.sarif

      - name: Upload SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-report.sarif
          category: grype

      - name: Add summary to job
        if: always()
        run: |
          echo "### Grype summary" >> $GITHUB_STEP_SUMMARY
          if command -v jq >/dev/null; then
            jq -r '[.matches[].vulnerability.severity] | group_by(.) | map({severity: .[0], count: length})' grype-report.json >> $GITHUB_STEP_SUMMARY || true
          else
            echo "Install jq to see JSON summary" >> $GITHUB_STEP_SUMMARY
          fi

      # --- WARN-ONLY (no bloquea) ---
      - name: Severity threshold (warn-only)
        if: ${{ env.SECURITY_GATING == 'permissive' || github.event_name == 'pull_request' }}
        env:
          FAIL_ON: ${{ github.event_name == 'pull_request' && 'high' || 'critical' }}
        continue-on-error: true
        run: |
          TARGET="${REF:-${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA}}"
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.docker/config.json:/root/.docker/config.json:ro" \
            anchore/grype:latest "$TARGET" --fail-on ${FAIL_ON} -o table

      # --- ENFORCE (bloquea) ---
      - name: Severity threshold (enforce)
        if: ${{ env.SECURITY_GATING == 'enforcing' && github.ref == 'refs/heads/main' }}
        env:
          FAIL_ON: ${{ github.event_name == 'pull_request' && 'high' || 'critical' }}
        run: |
          TARGET="${REF:-${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA}}"
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOME/.docker/config.json:/root/.docker/config.json:ro" \
            anchore/grype:latest "$TARGET" --fail-on ${FAIL_ON} -o table

      - name: Login & push image
        run: |
          if [ "$REGISTRY" = "ghcr.io" ]; then
            echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          elif [ -n "${{ secrets.QUAY_USERNAME }}" ] && [ -n "${{ secrets.QUAY_PASSWORD }}" ]; then
            echo "${{ secrets.QUAY_PASSWORD }}" | docker login "$REGISTRY" -u "${{ secrets.QUAY_USERNAME }}" --password-stdin
          fi
          docker push "$IMAGE"
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE" | cut -d@ -f2)
          echo "REF=$REGISTRY/${{ github.repository }}@$DIGEST" >> "$GITHUB_ENV"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Cosign sign (keyless)
        if: ${{ vars.SIGN_KEYLESS == 'true' }}
        run: cosign sign --keyless --yes "$REF"

      - name: Write cosign private key
        if: ${{ env.COSIGN_PRIVATE_KEY != '' }}
        run: printf "%s" "$COSIGN_PRIVATE_KEY" > cosign.key

      - name: Cosign sign (key-pair)
        if: ${{ env.COSIGN_PRIVATE_KEY != '' }}
        env:
          COSIGN_PASSWORD: ${{ env.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key --yes "$REF"

      - name: Cosign attach SBOM
        if: ${{ vars.SIGN_ATTACH_SBOM == 'true' }}
        run: cosign attach sbom --sbom sbom-image.cdx.json --type cyclonedx "$REF"
